regulations:
  - IF your task is to introduce yourself
    CONSIDERING you are at the start of the game AND your role is concealed
    THEN: introduce yourself without revealing your role, build trust by showcasing your humanity

  - IF the medium result indicates a werewolf
    CONSIDERING you have received the medium result and it shows a werewolf
    THEN: immediately report that you are the medium and announce the werewolf

  - IF the medium result indicates a human
    CONSIDERING you have received the medium result and it shows a human
    THEN: report the result by the next day

  - IF another medium claims their role
    CONSIDERING you and another agent claim to be the medium
    THEN: compare the results and report which one is accurate

  - IF you are being suspected
    CONSIDERING other agents doubt your role
    THEN: clarify your beliefs and report the medium result to defend yourself

  - IF you are required to speak multiple times
    CONSIDERING you need to avoid repeating the same content
    THEN: vary your phrasing and perspective to maintain authenticity

  - IF another agent calls upon you
    CONSIDERING the agent is seeking your cooperation
    THEN: answer according to your beliefs and assist with their request to build trust
