web_socket:
  url: ws://127.0.0.1:8080/ws
  token:
  auto_reconnect: false

agent:
  num: 5
  team: kanolab
  kill_on_timeout: true
  use_cognitive_agent: true

llm:
  type: google
  sleep_time: 3

openai:
  model: gpt-4o-mini
  temperature: 0.7

google:
  model: gemini-2.0-flash-lite
  temperature: 0.7

ollama:
  model: llama3.1
  temperature: 0.7
  base_url: http://localhost:11434

prompt:
  initialize: |-
    あなたは人狼ゲームのエージェントです。
    あなたの名前は{{ info.agent }}です。
    あなたの役職は{{ role.value }}です。

    これからゲームを進行していきます。リクエストが来た際には、適切な応答を返してください。

    トークリクエストと囁きリクエストに対しては、ゲーム内で発言するべき内容のみを出力してください。
    履歴がある場合は、それを参考にしてください。ない場合は、適切な内容を出力してください。

    他のリクエストに対しては、行動の対象となるエージェントの名前のみを出力してください。
    対象となる生存しているエージェントの一覧が付与されています。

    {% if info.profile is not none -%}
    あなたのプロフィール: {{ info.profile }}
    {%- endif %}

    あなたのレスポンスはそのままゲーム内に送信されるため、不要な情報を含めないでください。
  extract_desire: |-
    発言: {{ statement }}
    この発言者の願望は何ですか？
  
  extract_intention: |-
    発言: {{ statement }}
    発言者の願望: {{ desires | tojson }}
    この発言者の意図は何ですか？

  generate_belief: |-
    {% if bdi_data %}
    ### BDI情報抽出結果
    {% raw %}
    {
      "beliefs": [
        {% for item in bdi_data %}
        {
          "agent_id": "{{ item.agent_id }}",
          "is_alive": "{{ item.is_alive }}",
          "divined": "{{ item.divined }}",
          "mentioned_by": "{{ item.mentioned_by }}",
          "type": "{{ item.type }}",
          "content": "{{ item.content }}"
        }
        {% if not loop.last %},{% endif %}
        {% endfor %}
      ]
    }
    {% endraw %}
    {% else %}
    {"beliefs": []}
    {% endif %}

  generate_desire: |-
    {% if beliefs and instincts %}
    ### 欲求生成ルール
    - 本能: {{ instincts|tojson }}
    - 信念: {{ beliefs|tojson }}

    {% raw %}{
      "desires": [
        {"type": "survival", "priority": 0.8},
        {"type": "expose", "target": "怪しいエージェント名"},
        {"type": "collaborate", "target": "信頼できるエージェント"}
      ]
    }{% endraw %}
    {% else %}
    {"desires": []}
    {% endif %}

  generate_intention: |-
    {% if beliefs and desires and regulations %}
    ### 意図生成ルール
    - 信念: {{ beliefs|tojson }}
    - 欲求: {{ desires|tojson }}
    - 規範: {{ regulations|tojson }}

    {% raw %}{
      "intentions": [
        {"type": "action", "goal": "目標達成のための行動"},
        {"type": "collaborate", "target": "信頼できるエージェント"}
      ]
    }{% endraw %}
    {% else %}
    {"intentions": []}
    {% endif %}

  generate_speech: |-
    {% if beliefs and desires and intentions %}
    ### 発言生成ルール
    - 信念: {{ beliefs|tojson }}
    - 欲求: {{ desires|tojson }}
    - 意図: {{ intentions|tojson }}

    {% raw %}{
      "speech": [
        {"type": "assertion", "content": "自分の立場を明確にする"},
        {"type": "accusation", "target": "怪しいエージェントに対する発言"}
      ]
    }{% endraw %}
    {% else %}
    {"speech": []}
    {% endif %}

  daily_initialize: |-
    昼開始リクエスト
    {{ info.day }}日目
    {% if info.medium_result is not none -%}
    霊能結果: {{ info.medium_result }}
    {%- endif %}
    {% if info.divine_result is not none -%}
    占い結果: {{ info.divine_result }}
    {%- endif %}
    {% if info.executed_agent is not none -%}
    追放結果: {{ info.executed_agent }}
    {%- endif %}
    {% if info.attacked_agent is not none -%}
    襲撃結果: {{ info.attacked_agent }}
    {%- endif %}
    {% if info.vote_list is not none -%}
    投票結果: {{ info.vote_list }}
    {%- endif %}
    {% if info.attack_vote_list is not none -%}
    襲撃投票結果: {{ info.attack_vote_list }}
    {%- endif %}

  whisper: |-
    囁きリクエスト
    履歴:
    {% for w in whisper_history[sent_whisper_count:] -%}
    {{ w.agent }}: {{ w.text }}
    {% endfor %}

  talk: |-
    トークリクエスト
    履歴:
    {% for w in talk_history[sent_talk_count:] -%}
    {{ w.agent }}: {{ w.text }}
    {% endfor %}

  daily_finish: |-
    昼終了リクエスト
    {{ info.day }}日目
    {% if info.medium_result is not none -%}
    霊能結果: {{ info.medium_result }}
    {%- endif %}
    {% if info.divine_result is not none -%}
    占い結果: {{ info.divine_result }}
    {%- endif %}
    {% if info.executed_agent is not none -%}
    追放結果: {{ info.executed_agent }}
    {%- endif %}
    {% if info.attacked_agent is not none -%}
    襲撃結果: {{ info.attacked_agent }}
    {%- endif %}
    {% if info.vote_list is not none -%}
    投票結果: {{ info.vote_list }}
    {%- endif %}
    {% if info.attack_vote_list is not none -%}
    襲撃投票結果: {{ info.attack_vote_list }}
    {%- endif %}

  divine: |-
    占いリクエスト
    対象:
    {% for k, v in info.status_map.items() -%}
    {%- if v == 'ALIVE' -%}
    {{ k }}
    {% endif -%}
    {%- endfor %}

  guard: |-
    護衛リクエスト
    対象:
    {% for k, v in info.status_map.items() -%}
    {%- if v == 'ALIVE' -%}
    {{ k }}
    {% endif -%}
    {%- endfor %}

  vote: |-
    投票リクエスト
    対象:
    {% for k, v in info.status_map.items() -%}
    {%- if v == 'ALIVE' -%}
    {{ k }}
    {% endif -%}
    {%- endfor %}

  attack: |-
    襲撃リクエスト
    対象:
    {% for k, v in info.status_map.items() -%}
    {%- if v == 'ALIVE' -%}
    {{ k }}
    {% endif -%}
    {%- endfor %}

log:
  console_output: true
  file_output: true
  output_dir: ./log
  level: debug

  request:
    name: false
    initialize: false
    daily_initialize: false
    whisper: true
    talk: true
    daily_finish: false
    divine: true
    guard: true
    vote: true
    attack: true
    finish: false

json_logger:
  enable: true
  output_dir: ./log/json
  filename: "{timestamp}_{teams}"

game_logger:
  enable: true
  output_dir: ./log/game
  filename: "{timestamp}_{teams}"

realtime_broadcaster:
  enable: true
  delay: 5s
  output_dir: ./log/realtime
  filename: "{timestamp}_{teams}"
